allowBuilds:
  esbuild: true
overrides:
  '@deepseek-ai/cordis': link:D:/Projects/deepseek-harness/dsh/vendor/cordis
  '@deepseek-ai/dsh-authorization': link:D:/Projects/deepseek-harness/dsh/packages/credentials/authorization
  '@deepseek-ai/dsh-credentials': link:D:/Projects/deepseek-harness/dsh/packages/credentials/credentials
  '@deepseek-ai/dsh-llm': link:D:/Projects/deepseek-harness/dsh/packages/llm/llm
  '@deepseek-ai/dsh-settings': link:D:/Projects/deepseek-harness/dsh/packages/settings/settings
  '@deepseek-ai/dsh-tools': link:D:/Projects/deepseek-harness/dsh/packages/core/tools
  '@deepseek-ai/dsh-client-locale': link:D:/Projects/deepseek-harness/dsh/packages/client/locale
  '@deepseek-ai/dsh-client-store': link:D:/Projects/deepseek-harness/dsh/packages/client/store
  '@deepseek-ai/dsh-client-ui-renderer': link:D:/Projects/deepseek-harness/dsh/packages/client/ui-renderer
  '@deepseek-ai/dsh-client-ui-settings-plugins': link:D:/Projects/deepseek-harness/dsh/packages/client/ui-settings-plugins
  '@deepseek-ai/dsh-client-ui-slots': link:D:/Projects/deepseek-harness/dsh/packages/client/ui-slots
